### ISSUE TITLE
Update ODESUDI logo

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#32]
Transparent .png of ODESUDI logo to be supplied by Sobanukirwa team so that this logo does not appear on a white background at the bottom of each sobanukirwa.rw page.

**Comment by StephenAbbott** [comment]
OK. Will chase this

**Comment by StephenAbbott** [comment]
Hi @garethrees. I couldn't get the original .psd file but I have reedited the image so that it is hopefully better now. Could you try this .png instead? 

![odesudi logo updated](https://cloud.githubusercontent.com/assets/1506468/5700544/877602b4-9a48-11e4-9d7d-5e4fa7ac49c8.png)

**Comment by StephenAbbott** [comment]
Hi @garethrees . I couldn't get the original .psd file but I have reedited the image so that it is hopefully better now. Could you try this .png instead? 

![odesudi logo updated](https://cloud.githubusercontent.com/assets/1506468/5700574/eefe6b2e-9a48-11e4-9b25-a5645310cd0f.png)

**Comment by garethrees** [comment]
Hey @StephenAbbott. That png is rendered on to a white background.

**Comment by StephenAbbott** [comment]
Apologies @garethrees. Here's that image again on a transparent background

![odesudi logo transparent](https://cloud.githubusercontent.com/assets/1506468/5719971/6c3c4ccc-9b26-11e4-8fc6-07948b168d43.png)

**Comment by garethrees** [comment]
Still has the same issues:

![screen shot 2015-01-13 at 11 21 00](https://cloud.githubusercontent.com/assets/282788/5720017/510eb77e-9b16-11e4-944a-a9e40c763d7d.png)

**Comment by garethrees** [comment]
@stevenday has fixed this for us!

![screen shot 2015-01-13 at 13 33 37](https://cloud.githubusercontent.com/assets/282788/5721371/d27ca3fe-9b28-11e4-8a32-49afda7e5dbf.png)
![lexizmi](https://cloud.githubusercontent.com/assets/282788/5721375/d9ecef86-9b28-11e4-9858-5b182c8dddd9.png)

**Comment by StephenAbbott** [comment]
Looks great to me. Thanks @stevenday and @garethrees. Sorry for all the faff.
