### ISSUE TITLE
Add Kinyarwanda translation of Alaveteli app.po file to sobanukirwa.rw

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#39]
A 98% complete Kinyarwanda translation of the Alaveteli app.po file is now up on Transifex and we're working on polishing off the outstanding 23 lines which need translating: https://www.transifex.com/projects/p/alaveteli/viewstrings/#rw/apppot/7702954

Could @garethrees please add the .rw translation files to sobanukirwa.rw?

Separate Github issue being raised for completing translation of /help pages into Kinyarwanda.

**Comment by garethrees** [comment]
Will hotfix master later this week to include these.

**Comment by garethrees** [comment]
Done in https://github.com/mysociety/alaveteli/commit/70b67224f1afbfae2e22658a510e19bc29dfbbf1
