### ISSUE TITLE
Translate /help pages [Kinyarwanda]

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#40]
Create the file with the locale prefix in the filename:

about.html.erb
about.rw.html.erb

**Comment by garethrees** [comment]
Are these available for us yet, or would you like us to create them for you to modify?

**Comment by StephenAbbott** [comment]
Hi @garethrees. Similar to the issue of French translation of /help pages (https://github.com/mysociety/sobanukirwa-theme/issues/29), these translations are a work in progress. Clarisse, our translator, is doing them offline at the moment so it would be very useful if you can create /rw versions of the help page .erb files. Then I'll be updating those files with Clarisse's translation once they're complete as she's not familiar with Github. That OK?

**Comment by StephenAbbott** [comment]
New .rw files created in https://github.com/Sobanukirwa/sobanukirwa-theme/tree/master/lib/views/help and completed with Kinyarwanda translations of /help pages:

https://github.com/Sobanukirwa/sobanukirwa-theme/blob/master/lib/views/help/api.rw.html.erb
https://github.com/Sobanukirwa/sobanukirwa-theme/blob/master/lib/views/help/credits.rw.html.erb
https://github.com/Sobanukirwa/sobanukirwa-theme/blob/master/lib/views/help/officers.rw.html.erb
https://github.com/Sobanukirwa/sobanukirwa-theme/blob/master/lib/views/help/requesting.rw.html.erb
https://github.com/Sobanukirwa/sobanukirwa-theme/blob/master/lib/views/help/alaveteli.rw.html.erb
https://github.com/Sobanukirwa/sobanukirwa-theme/blob/master/lib/views/help/privacy.rw.html.erb

Unfortunately I somehow missed out on three of the /help pages when commissioning our translator to work on these so we don't have Kinyarwanda translations for the following pages:

https://github.com/Sobanukirwa/sobanukirwa-theme/blob/master/lib/views/help/_sidebar.rw.html.erb
https://github.com/Sobanukirwa/sobanukirwa-theme/blob/master/lib/views/help/about.rw.html.erb
https://github.com/Sobanukirwa/sobanukirwa-theme/blob/master/lib/views/help/contact.rw.html.erb
https://github.com/Sobanukirwa/sobanukirwa-theme/blob/master/lib/views/help/unhappy.rw.html.erb

I'm going to discuss this with Claude tomorrow to make a plan for how we can complete these translations ahead of next week's launch

**Comment by garethrees** [comment]
:+1: Excellent. I'll get these added today.

**Comment by garethrees** [comment]
Available versions added in https://github.com/mysociety/sobanukirwa-theme/commit/f0e9e3bfd02e95e955b140cef6ed01b4a00bc62d

**Comment by garethrees** [comment]
Deployed available translations: https://sobanukirwa.rw/rw/help/about

(note that the sidebar and about page have _not_ been translated yet)

**Comment by StephenAbbott** [comment]
Following rw.erb.html /help pages have now been translated into Kinyarwanda:
https://github.com/Sobanukirwa/sobanukirwa-theme/blob/master/lib/views/help/about.rw.html.erb
https://github.com/Sobanukirwa/sobanukirwa-theme/blob/master/lib/views/help/_sidebar.rw.html.erb
https://github.com/Sobanukirwa/sobanukirwa-theme/blob/master/lib/views/help/contact.rw.html.erb
https://github.com/Sobanukirwa/sobanukirwa-theme/blob/master/lib/views/help/unhappy.rw.html.erb

Could they please be deployed?

**Comment by garethrees** [comment]
Some minor bits missing on `lib/views/help/contact.rw.html.erb`:

- `<label class="form_label" for="contact_message">Include link to request:</label>` "Include link to request:"
- `<%= submit_tag "remove", :name => 'remove' %>` "remove"
- `<label class="form_label" for="contact_message">Include link to authority:</label>` "Include link to authority:"
- `<%= submit_tag "remove", :name => 'remove' %>`
- `<%= submit_tag "Oherereza ubutumwa uyu muryango", :disable_with => "Sending..." %>` "Sending…"

**Comment by garethrees** [comment]
Added in 6977a9da84587002a36ad2a143870528915c0e20 and deployed.

**Comment by StephenAbbott** [comment]
Fantastic. Thanks @garethrees. Looks great to me. Will get those more conversant with Kinyarwanda to double-check these pages over
