### ISSUE TITLE
Happy Christmas, Gareth!

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#41]
Both Claude and I are leaving Kigali soon to travel to Belgium/UK respectively for the festive break, so I just wanted to wish @garethrees a very merry Christmas and a happy new year.

Thanks for all the work that you've done to get sobanukirwa.rw to where it is now. We can't wait to let everyone see it in the new year.

![imgres](https://cloud.githubusercontent.com/assets/1506468/5467238/7cc8e1a8-85c4-11e4-90d4-e13ef1199790.jpg)

**Comment by garethrees** [comment]
Happy New Year! Time to take the decorations and cards down. Here's to the sobanukirwa.rw launch :wine_glass:!
