### ISSUE TITLE
Add French translation of Alaveteli app.po file to sobanukirwa.rw

### ISSUE THREAD

**Issue by Mikaclo** [mysociety/sobanukirwa-theme#42]
A 100% complete French translation of the Alaveteli app.po file is now up on Transifex:https://www.transifex.com/projects/p/alaveteli/resource/apppot/

Could @garethrees please add the .fr translation files to sobanukirwa.rw? @StephenAbbott 

Thank you.

**Comment by garethrees** [comment]
Will hotfix master later this week to include these.

**Comment by garethrees** [comment]
Done in https://github.com/mysociety/alaveteli/commit/70b67224f1afbfae2e22658a510e19bc29dfbbf1
