### ISSUE TITLE
Legal explanation/prompt at the start of all emails (French translation)

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#43]
In issue https://github.com/mysociety/sobanukirwa-theme/issues/11, @garethrees and @crowbot helped us to work out an automated line of text to add to each auto-generated email so that our users include details of the ATI law to information officers who may not be aware of the law.

Below is the French version of this same text. Could this please be added to all requests generated through the French translation of sobanukirwa.rw?

```
J'aimerai accéder cette information comme prévoit la loi numero 04/2013 en rapport avec l'accès a l'information.
```

**Comment by garethrees** [comment]
Fixed in 6a429f4
