### ISSUE TITLE
Legal explanation/prompt at the start of all emails (Kinyarwanda translation)

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#44]
In issue https://github.com/mysociety/sobanukirwa-theme/issues/11, @garethrees and @crowbot helped us to work out an automated line of text to add to each auto-generated email so that our users include details of the ATI law to information officers who may not be aware of the law.

Below is the Kinyarwanda version of this same text. Could this please be added to all requests generated through the Kinyarwanda translation of sobanukirwa.rw once this is generated on the site?

```
Nifuzaga gusaba amakuru nkuko byemewe tugendeye kw'itegeko numero 04/2013 ryatowe ku ya 8 Gashyantare 2013 rijyanye no guhabwa amakuru.
```

**Comment by garethrees** [comment]
Fixed in 3ca8bd8
