### ISSUE TITLE
Pull request to fix typo in updated requesting file

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#45]
https://github.com/Sobanukirwa/sobanukirwa-theme/commit/64dd6a91c9dbc227e1da57f90ceb48f9aa80431e

**Comment by garethrees** [comment]
I'll get this merged. Cheers.

**Comment by garethrees** [comment]
Added in 0df2a27a330dcec16754e9034b5668a8399ac48e
