### ISSUE TITLE
Centring the Contact us/Follow us/Like us links in site-wide footer

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#51]
The left-hand and right-hand columns in the site-wide footer are centred but the middle column seems to be left-aligned. Could this be changed so that the links are centred as well?

![image](https://cloud.githubusercontent.com/assets/1506468/5663143/b2319e0a-974b-11e4-8bc3-386aea96a8e5.png)

**Comment by garethrees** [comment]
Like this?

![screen shot 2015-01-12 at 10 52 49](https://cloud.githubusercontent.com/assets/282788/5701840/28369aa6-9a49-11e4-8f4c-eb6d4a6be187.png)

**Comment by StephenAbbott** [comment]
Looks great to me. Thanks @garethrees

**Comment by garethrees** [comment]
Fixed in 5a1ab1fc4db56ac5ae910ed5abe68d87cb913e07
