### ISSUE TITLE
Add sobanukirwa-theme app.pot files to sobanukirwa.rw

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#53]
Clarisse due to complete translation of final 60 lines of French and 60 lines of Kinyarwanda for Sobanukirwa by morning of Friday 16 January:

https://www.transifex.com/projects/p/sobanukirwa-theme/language/fr/
https://www.transifex.com/projects/p/sobanukirwa-theme/language/rw/

This issue is for those Transifex files to then be uploaded to sobanukirwa.rw ahead of beta launch.

**Comment by StephenAbbott** [comment]
These translation files are both 100% complete now: 
https://www.transifex.com/projects/p/sobanukirwa-theme/language/fr/
https://www.transifex.com/projects/p/sobanukirwa-theme/language/rw/

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/sobanukirwa-theme/commit/9ef55901b8b56d426dfb7af1563804437b93b91e
