### ISSUE TITLE
Change 'With the help of' footer text to 'In partnership with'

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#56]
Can we please update the footer text above the ODESUDI logo from 'With the help of' to 'In partnership with' as this is the language we've agreed to use with ODESUDI in our memorandum of understanding with them?

Do we need a French and Kinyarwanda translation of 'In partnership with' as well?

**Comment by garethrees** [comment]
> Can we please update the footer text above the ODESUDI logo from 'With the help of' to 'In partnership with' as this is the language we've agreed to use with ODESUDI in our memorandum of understanding with them?

No problem!

> Do we need a French and Kinyarwanda translation of 'In partnership with' as well?

Yep!

**Comment by StephenAbbott** [comment]
In partnership with translations cc @garethrees 
French = En partenariat avec
Kinyarwanda =  Ku bufatanye na

**Comment by garethrees** [comment]
English changed in https://github.com/mysociety/sobanukirwa-theme/commit/013339706120801d72d10a925c35a0130d423cdb

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/sobanukirwa-theme/commit/9ef55901b8b56d426dfb7af1563804437b93b91e
