### ISSUE TITLE
Add config/locale/rw.yml

### ISSUE THREAD

**Issue by garethrees** [mysociety/sobanukirwa-theme#57]
Get and add RW translation of https://raw.githubusercontent.com/svenfuchs/rails-i18n/master/rails/locale/en.yml

**Comment by garethrees** [comment]
Marking as a bug since some pages throw exceptions: https://sobanukirwa.rw/rw/body/list/all

**Comment by garethrees** [comment]
Fixed in https://github.com/mysociety/alaveteli/pull/2102

Currently deployed hotfix/0.20.0.4 while #2102 is under review:

```diff
-       git_ref => 'origin/master',
+       git_ref => 'origin/hotfix/0.20.0.4', # [gareth] temporarily deploy this while alaveteli#2102 is waiting review
```

**Comment by Mikaclo** [comment]
https://gist.github.com/Mikaclo/c1b5fd0c5ddea36000bc @garethrees the link takes you to the Kinyarwanda rw .yml file translation. @StephenAbbott

**Comment by garethrees** [comment]
Added and waiting review in https://github.com/mysociety/alaveteli/pull/2110
