### ISSUE TITLE
Redirect all team@sobanukirwa.rw mail to sobanukirwa@gmail.com

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#58]
Please cancel the redirect from team@sobanukirwa.rw which is sending emails to both mine and Claude's inbox and replace it with a redirect sending all mail to team@sobanukirwa.rw to sobanukirwa@gmail.com instead.

All mail to stephen@sobanukirwa.rw should still be redirected to stephendabbott@gmail.com and all mail to claude@sobanukirwa.rw should be redirected to mikaclau@gmail.com.

**Comment by garethrees** [comment]
Done
