### ISSUE TITLE
All category description links appearing on authority pages link to English authority index

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#59]
I've just noticed that the category description links on authority pages all link to the English authority pages on sobanukirwa.rw no matter whether the user has already used the language switcher.

So in all three of the following cases, the ministerial department link under the page title takes the user to the English ministries tagged list even though I've changed the text for each language version:

https://sobanukirwa.rw/body/minipresirep
https://sobanukirwa.rw/rw/body/minipresirep
https://sobanukirwa.rw/fr/body/minipresirep

Can this functionality be updated to pass the /en, /fr or /rw prefixes to the authority/category list tags so that the user stays within their chosen language settings?

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli/issues/2112, https://github.com/mysociety/alaveteli/blob/rails-3-develop/app/models/public_body.rb#L351-L352 generates the URL in the model with no regard for the current locale. Sigh ;).
