### ISSUE TITLE
Upload Google HTML verification file to let Stephen verify ownership for Webmaster tools

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#62]
HTML verification file should be available from link below:

**Comment by garethrees** [comment]
Added to `WEB_ROOT/rwanda.alaveteli.org/shared/public/googlef132c1084171aa88.html`

https://sobanukirwa.rw/googlef132c1084171aa88.html

**Comment by StephenAbbott** [comment]
Apologies but I think the SSL certificate update from http:// to https:// has confused Google Webmaster tools so they won't let me verify the site using the verification file you uploaded.

Could you upload this file to web_root instead?

https://www.google.com/webmasters/verification/verification-file-dl?hl=en&siteUrl=https://sobanukirwa.rw/&security_token=3nN7LTXAUe4f7uqFL4DLtzwnMb0:1421912236184

**Comment by garethrees** [comment]
Updated https://sobanukirwa.rw/googleb3c6c287148fe641.html
