### ISSUE TITLE
Reimport Transifex app.po files to correct small typos on /fr and /rw versions of sobanukirwa.rw

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#74]
Here's a list of the Transifex app.po files that Claude and I have updated which need to be re-imported on to the website:

https://www.transifex.com/projects/p/sobanukirwa-theme/language/fr/
https://www.transifex.com/projects/p/sobanukirwa-theme/language/rw/
https://www.transifex.com/projects/p/sobanukirwa-theme/language/en/
https://www.transifex.com/projects/p/alaveteli/language/fr/
https://www.transifex.com/projects/p/alaveteli/language/rw/

And here are the Github .erb pull requests I've raised to correct help pages (Claude may submit more in the comments on this issue tonight):
https://github.com/mysociety/sobanukirwa-theme/pull/72
https://github.com/mysociety/sobanukirwa-theme/pull/71

**Comment by garethrees** [comment]
I've updated the FR (47eab39) and rwRW(e84a4a3) theme translations.

Unfortunately you can't edit the EN translations through transifex, since the strings need to match up with the source code.

Could you let us know the EN phrases you want changed and I'll do them manually.

**Comment by StephenAbbott** [comment]
I fear that I was just being a bit OCD and had changed Access to Information to access to information (all lower case). Clearly not a big issue so happy to close this one.

**Comment by garethrees** [comment]
We'll update the Alaveteli core translations in https://github.com/mysociety/alaveteli/issues/2049
