### ISSUE TITLE
Embedded Twitter timeline for @Sobanukirwa not appearing on right-hand side of /blog page

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#78]
Embed code missing or broken? https://sobanukirwa.rw/blog

**Comment by garethrees** [comment]
We'll need a [Twitter Widget ID](https://twittercommunity.com/t/how-do-you-get-twitter-widget-id/20498) for that.

**Comment by StephenAbbott** [comment]
Here's the Twitter widget ID: 560736173279444992

**Comment by garethrees** [comment]
Added and deployed! :+1:
