### ISSUE TITLE
Update 'In partnership with' text in site footer to 'Co-created by'

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#79]
In accordance with the memorandum of understanding we've signed with our civil society partners ODESUDI, we'd like to update the text displayed on the sobanukirwa.rw site-wide footer to remove the 'In partnership with' text and replace it with the relevant translation of 'Co-created by' which are displayed below:

English: Co-created by
Kinyarwanda: Co-créé par
French: Ku bufutanye na

Apologies to @garethrees for asking to change this language again.

**Comment by garethrees** [comment]
Fixed in f8386b3a677ab41592b339ea9b92b86fc2d5b652 :cake:

**Comment by StephenAbbott** [comment]
Oops. I mixed up a couple of the translations:

English: Co-created by
Kinyarwanda: Ku bufutanye na
French: Co-créé par
