### ISSUE TITLE
Replace 'A project by Sobanukirwa' in footer with Indigo Trust text/logo

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#81]
In the site-wide footer for sobanukirwa.rw, we like to replace the 'A project by Sobanukirwa' section with some text and a logo showing that we're supported by the Indigo Trust.

We'd like to display text saying 'Supported by' in our three languages above the Indigo Trust logo. Unfortunately I don't think we can cut out the logo as it uses black text on a white background so this would not be readable against a grey background. 

Here is the logo: ![indigo trust logo](https://cloud.githubusercontent.com/assets/1506468/6916106/c584ad74-d799-11e4-97b9-c986a7d92a58.jpg)

And we'd like it to link to the following funding blogpost: http://indigotrust.org.uk/2015/03/30/new-grant-rwandan-foi-platform/

Here is 'Supported by' translated into the three languages we use on Sobanukirwa:

English = Supported by
Kinyarwanda = Yatewe inkunga na
French = Soutenu par

**Comment by garethrees** [comment]
Hey @StephenAbbott,

Did you want this _in addition to_ the existing Sobanukirwa logo, or to completely replace that column?

Cheers.

**Comment by StephenAbbott** [comment]
Hi @garethrees. We'd like this to completely replace that column. Thanks

**Comment by garethrees** [comment]
Deployed! :tada:

**Comment by StephenAbbott** [comment]
Thanks @garethrees! Looks great

![ali-gee-thumbs-up](https://cloud.githubusercontent.com/assets/1506468/7178249/9b057204-e42d-11e4-9b86-af4ea2522a80.jpg)
