### ISSUE TITLE
Update sobanukirwa.rw to incorporate 39 new lines of text in Kinyarwanda/French

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#82]
Team Sobanukirwa have now translated the 39 new lines of text recently added to Alaveteli into Kinyarwanda and French.

The Alaveteli app.po files for both these languages are now 100% complete again on Transifex:
https://www.transifex.com/projects/p/alaveteli/language/fr/
https://www.transifex.com/projects/p/alaveteli/language/rw/

Could @garethrees or @crowbot please reimport these app.po files whenever they have time to update sobanukirwa.rw? Thanks!

**Comment by garethrees** [comment]
New translations have been pulled and hotfixed against 0.21. Might jump straight to release 0.22 when available. Marking as 'Awaiting deploy' since the next deploy will update the translations.
