### ISSUE TITLE
Add Tumenye logo to sobanukirwa.rw footer

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#84]
Now that we've got Tumenye's website up and running at http://www.tumenye.rw, we'd like to add the Tumenye logo to the footer of https://sobanukirwa.rw and make it link to http://www.tumenye.rw.

Is there a way to put the Tumenye logo side-by-side with the ODESUDI logo so that the Indigo Trust logo, ODESUDI logo and Tumenye logo are all displayed in the footer? Thanks

![logo](https://cloud.githubusercontent.com/assets/1506468/8452839/9d3d5bca-1fee-11e5-916a-1b1b216e1481.png)

cc @garethrees @crowbot

**Comment by garethrees** [comment]
Hey Stephen,  

http://www.tumenye.rw/ looks great – congrats!

Could you just add a sketch (either paper or https://www.draw.io/) of how you
want the layout to look.

Can’t quite visualise what you mean.

Cheers,  

--  
Gareth Rees
gareth@mysociety.org (mailto:gareth@mysociety.org)

**Comment by StephenAbbott** [comment]
I need to get you a proper transparent .png of the Tumenye logo with the Tumenye name underneath but here are rough ideas of what I was trying to say:

Desktop view footer

![desktop view](https://cloud.githubusercontent.com/assets/1506468/8481862/075ec5e6-20e6-11e5-8b21-dade80a03f2f.png)


Mobile view footer

![mobile view](https://cloud.githubusercontent.com/assets/1506468/8482223/7abd2972-20e8-11e5-9e82-0ef07075fa45.png)

**Comment by garethrees** [comment]
Ah, gotcha. I'd imagine that's possible :)

**Comment by StephenAbbott** [comment]
Here's the transparent .png of the full Tumenye logo and the link is http://www.tumenye.rw/

![transparent cropped](https://cloud.githubusercontent.com/assets/1506468/8520894/dec0b5a8-23de-11e5-8616-4d383b354056.png)

**Comment by garethrees** [comment]
Do you want us to:

a. cut it up so that the logotype is below the logomark?
b. just use the logomark?

I think if we do 'a', the dark blue will be really hard to read on the black.
It might be better to use either white or the blue in the highest line in the mark for the logotype.

**Comment by StephenAbbott** [comment]
Our designer might kill me but I've gone with a). Here's the updated logo:

![logo for sobanukirwa footer](https://cloud.githubusercontent.com/assets/1506468/8522428/4bda921c-23ee-11e5-8fe0-151be28d6904.png)

**Comment by garethrees** [comment]
Looks good to me. Could you provide that on a transparent png? Looks like there are some artifacts from the editing you've made:

![4bda921c-23ee-11e5-8fe0-151be28d6904](https://cloud.githubusercontent.com/assets/282788/8522687/4894a13e-23e8-11e5-83d1-b96273df1d2b.png)

We can wait until your designer has chance to do this if you'd prefer?

**Comment by StephenAbbott** [comment]
Ahem. I'll try that again. And here it is as a transparent .png with those artifacts removed. Hope this is good enough. The designer's not on staff (and has moved away from Kigali) so I'm updating this myself: 

![transparent logo for sobanukirwa footer](https://cloud.githubusercontent.com/assets/1506468/8523447/bf80822e-23f5-11e5-80bf-97cbe15bd80b.png)
