### ISSUE TITLE
504 Gateway Time-Out message for Sobanukirwa request pages

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#85]
Experienced at 9:20pm on Tuesday 15 September 2015 when browsing sobanukirwa.rw using latest version of Google Chrome. No recent commits to Sobanukirwa-theme. Any idea what's causing that @garethrees?

**Comment by garethrees** [comment]
https://groups.google.com/a/mysociety.org/forum/#!topic/international/SgeifsQXq7k
