### ISSUE TITLE
Replace ODESUDI logo in Sobanukirwa footer with new .png version

### ISSUE THREAD

**Issue by StephenAbbott** [mysociety/sobanukirwa-theme#86]
![odesudi logo](https://cloud.githubusercontent.com/assets/1506468/10687889/b3b5f318-7970-11e5-8075-13bddf376ac4.png)

**Comment by garethrees** [comment]
Updated, but might be worth them providing a version with white text so that its more readable on the black background?

![screen shot 2015-10-27 at 12 57 48](https://cloud.githubusercontent.com/assets/282788/10758610/6c36e8de-7caa-11e5-9fa2-fed2c8cd34ca.png)

**Comment by StephenAbbott** [comment]
Thanks @garethrees. I'll pass that on
