### ISSUE TITLE
Upgrade to version 0.25

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/sobanukirwa-theme#88]
Partner is happy for us to upgrade. 

They will find someone to translate missing strings:

Kinyarwanda (128 strings need to be translated): https://www.transifex.com/mysociety/alaveteli/viewstrings/#rw/apppot/92362970?translated=no

French (119 strings need to be translated): https://www.transifex.com/mysociety/alaveteli/viewstrings/#fr/apppot/92362970?translated=no

**Comment by garethrees** [comment]
RE: `en_RW`, looks like we just imported `en/app.po` and then changed FOI to ATI (etc). Just need to repeat the process for the latest `en/app.po` and commit.

**Comment by lizconlan** [comment]
ToDo:
- [ ] upgrade theme code
- [ ] update `en/app.po` file ([see above](https://github.com/mysociety/sobanukirwa-theme/issues/88#issuecomment-243742889))
- [ ] preserve current translations
- [ ] apply new translations when ready

**Comment by Gemmamysoc** [comment]
Message from Claude on 8th Sept:

"Thanks for the follow-up email. We have a number of meetings scheduled by the end this month to increase  the website awareness/usage. From how it goes and the feedback we receive we shall then look into finding a translator to help us with the translation. "

**Comment by Gemmamysoc** [comment]
Claude is receiving an error on Kinyarwandan untranslated strings on Transifex: 
<img width="1280" alt="screen shot 2016-11-07 at 15 10 25" src="https://cloud.githubusercontent.com/assets/6806067/20060893/3cec6850-a4f5-11e6-8fb1-d339fefbfaac.png">

**Comment by garethrees** [comment]
Pretty strange – might be worth him (or us) getting in touch with transifex to see what they suggest.
